### ISSUE TITLE
[Task] CI fails to download `-core`

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-reports#198]
https://github.com/cryostatio/cryostat-reports/actions/runs/7625164851/job/20768861530?pr=197

```
Error:  Failed to execute goal on project cryostat-reports: Could not resolve dependencies for project io.cryostat:cryostat-reports:jar:2.5.0-SNAPSHOT: Failed to collect dependencies at io.cryostat:cryostat-core:jar:2.27.0: Failed to read artifact descriptor for io.cryostat:cryostat-core:jar:2.27.0: The following artifacts could not be resolved: io.cryostat:cryostat-core:pom:2.27.0 (absent): Could not transfer artifact io.cryostat:cryostat-core:pom:2.27.0 from/to github (https://maven.pkg.github.com/cryostatio/cryostat-core): status code: 401, reason phrase: Unauthorized (401) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Error: Process completed with exit code 1.
```

Related to #81

**Comment by andrewazores** [comment]
Still not working. Not sure what else I have missed. @aali309 @mwangggg any ideas?

**Comment by mwangggg** [comment]
oh this might be the problem we encountered earlier where the CI isn't actually using the latest cached maven files?

**Comment by andrewazores** [comment]
I'll give it a shot.

**Comment by andrewazores** [comment]
Still no luck :/

https://github.com/cryostatio/cryostat-reports/actions/runs/7660225314/job/20877067250

**Comment by mwangggg** [comment]
I think maybe the core image needs to be built and cached here? There's no way for the CI to obtain the -core jar  otherwise and I think that's why it's complaining... this only seems to have started happening after we switched to the default GITHUB_TOKEN

**Comment by andrewazores** [comment]
It shouldn't need to be built, just downloading it from GH mvn should be enough. I'm not sure why the token suddenly stopped working, it looks like it broke on its own on another Dependabot update PR, so I guess it expired or was revoked? It was recently updated though. I figured I could get around that by just using the same token we use elsewhere, but I guess not.

Anyway, we're in progress with getting `-core` builds onto Maven Central, so that will clear up all these authentication annoyances. Maybe we just wait for that.

**Comment by mwangggg** [comment]
oh do you need to include `env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` to that step??=
