### ISSUE TITLE
Reports pod fails to start on some clusters due to entrypoint permissions

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-reports#58]
I also got a bit of an issue when creating a report replica as pod seems to in `CrashLoopBackOff` with logs show:

```bash
exec /deployments/run-java.sh: permission denied
```

I am using Cluster Bot with OCP 4.11.1

_Originally posted by @tthvo in https://github.com/cryostatio/cryostat-operator/issues/499#issuecomment-1324156828_

**Comment by ebaron** [comment]
We should update our Dockerfile to use the OpenJDK UBI images.

**Comment by tthvo** [comment]
I suppose these images: `registry.access.redhat.com/ubi8/openjdk-17-runtime:some-tag`? Also, which tag are we targetting?

**Comment by tthvo** [comment]
Ah right! I could help update to `registry.access.redhat.com/ubi8/openjdk-17:1.14` then.

**Comment by ebaron** [comment]
Thanks, sounds good.
